{"name": "test_login_lockedUser", "status": "passed", "start": 1695739027412, "stop": 1695739028221, "uuid": "7ed95c9d-a71f-433a-aa02-12e52b9b80e6", "historyId": "4f45079f1e2a645a7954c21db8f59309", "testCaseId": "4f45079f1e2a645a7954c21db8f59309", "fullName": "test_saucedemo_block9#test_login_lockedUser", "labels": [{"name": "story", "value": "Тест нахождения контейнера с ошибкой"}, {"name": "feature", "value": "Тест входа под заблокированным пользователем"}, {"name": "suite", "value": "test_saucedemo_block9"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "12660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_saucedemo_block9"}]}